CREATE DATABASE lockbox;

USE  lockbox;

CREATE TABLE users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(30) NOT NULL,
    role ENUM('user','admin') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notes(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(80) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  user_id INTEGER NOT NULL,

  FOREIGN KEY (user_id) REFERENCES users(id) 
);